// Generated by CoffeeScript 1.6.2
(function() {
  var addClearDiv, addDevInfo, blockSum, block_counter, block_set, blocks, bookMarks, bookmarkIt, createBlocks, createBookmark, createButtons, createHistory, filter, filterArray, folders, googlevisible, hideInactiveTasks, idToRef, lastTitle, lastUrl, lastVid, loadBookmarks, loadHistory, logInfo, max, min, processHistoryItems, processVisitItems, processed, reload, renderItem, renderTaskMenu, shortenTitle, siteHistory, specialise, start, storedBookmarks, storedContexts, tabArray, tabconnections, thelastTitle, thelastURL, toggleActiveState, urltoblock, v_max, visitIdAufSID;

  processed = 0;

  tabconnections = [];

  lastVid = 0;

  lastUrl = "";

  siteHistory = [];

  visitIdAufSID = [];

  idToRef = {};

  urltoblock = {};

  block_counter = 0;

  block_set = 0;

  blockSum = 0;

  blocks = [];

  lastTitle = "";

  filterArray = ["adf.ly"];

  loadHistory = function(callbackFn) {
    processed = 0;
    tabconnections = [];
    lastVid = 0;
    lastUrl = "";
    siteHistory = [];
    visitIdAufSID = [];
    idToRef = {};
    urltoblock = {};
    block_counter = 0;
    block_set = 0;
    blockSum = 0;
    blocks = [];
    return chrome.storage.local.get("tabConnections", function(result) {
      if (result.tabConnections) {
        tabconnections = result.tabConnections;
      } else {
        tabconnections = [];
      }
      return processHistoryItems(callbackFn);
    });
  };

  processHistoryItems = function(callbackFn) {
    var date, daydate, endtime, microsecondsPerDay, starttime, time;

    time = filter.time;
    processed = 0;
    date = new Date();
    daydate = date.getTime() - ((((date.getHours() + 1) * 60 + date.getMinutes()) * 60 + date.getSeconds()) * 1000);
    microsecondsPerDay = 1000 * 60 * 60 * 24;
    endtime = daydate - (microsecondsPerDay * (time - 1));
    starttime = daydate - (microsecondsPerDay * (30 + time));
    return chrome.history.search({
      text: filter.query,
      startTime: starttime,
      endTime: endtime,
      maxResults: filter.results
    }, function(historyItems) {
      return (historyItems.reverse()).forEach(function(site) {
        processed++;
        return chrome.history.getVisits({
          url: site.url
        }, function(visitItems) {
          return processVisitItems(site, visitItems, callbackFn);
        });
      });
    });
  };

  processVisitItems = function(site, visitItems, callbackFn) {
    var bookmark, context, count, i, id, ref, referrer, siteItem, tab, testurl, time, type, url, vid, vids, _i, _len;

    referrer = vids = [];
    id = site.id;
    url = site.url;
    if (/data:/.test(url)) {
      null;
    } else {
      vid = visitItems[visitItems.length - 1].visitId;
      ref = visitItems[visitItems.length - 1].referringVisitId;
      type = visitItems[visitItems.length - 1].transition;
      time = visitItems[visitItems.length - 1].visitTime;
      count = site.visitCount;
      for (_i = 0, _len = visitItems.length; _i < _len; _i++) {
        i = visitItems[_i];
        if (i.visitId > vid - 300) {
          if (tabconnections[i.visitId] != null) {
            referrer.push(tabconnections[+i.visitId]);
          }
          if (i.referringVisitId !== "0") {
            referrer.push(i.referringVisitId);
          }
          visitIdAufSID[i.visitId] = id;
        }
      }
      idToRef[id] = referrer;
      testurl = url.split("//")[1];
      url = testurl.substr(0, 10);
      if ((type === "link" || type === "form_submit") && (lastVid === ref || lastUrl === url)) {
        urltoblock[url] = block_set;
      } else {
        if ((urltoblock[url] != null) && url !== "www.google" && url !== "www.youtub") {
          block_set = urltoblock[url];
        } else {
          block_counter++;
          blocks[block_counter] = {
            "id": block_counter,
            "context": "",
            "time": "",
            "processed": false,
            "google": false
          };
          if (/google/.test(url)) {
            blocks[block_counter].google = true;
          }
          block_set = block_counter;
          urltoblock[url] = block_set;
        }
      }
      lastVid = vid;
      lastUrl = url;
      context = "";
      bookmark = void 0;
      if (bookMarks[site.url] != null) {
        context = bookMarks[site.url].context;
        bookmark = bookMarks[site.url].bid;
        blocks[block_set].context = context;
      }
      blocks[block_set].time = time;
      tab = tabArray[site.url] != null ? tabArray[site.url] : "";
      if (site.title === "" || (lastTitle !== site.title && !(jQuery.inArray(url.substr(0, 6), filterArray) >= 0))) {
        siteItem = {
          sid: id,
          vid: vid,
          url: site.url,
          title: site.title,
          type: type,
          ref: ref,
          relevance: count,
          time: time,
          block: block_set,
          context: context,
          tab: tab,
          bid: bookmark
        };
        siteHistory[id] = siteItem;
      } else {
        null;
      }
      lastTitle = site.title;
    }
    processed--;
    if (processed === 0) {
      blockSum = block_counter;
      return callbackFn();
    }
  };

  logInfo = function(infoarray) {
    var i, info, k, siteinfo;

    siteinfo = $("<div>");
    for (k in infoarray) {
      i = infoarray[k];
      info = $("<div>");
      info.text(i);
      info.addClass("infotext");
      if (k === "0") {
        info.addClass("title");
      }
      siteinfo.append($(info));
    }
    return $("#historycontent").append($(siteinfo));
  };

  /*
  createBlocks = () ->
    block = 1
    for id,val of siteHistory
      processed++
      for v in idToRef[id]
        processed++
        if visitIdAufSID[v]?
          if siteHistory[visitIdAufSID[v]].block != 0 #block wird geerbt
            if val.block != 0
              for s in siteHistory # noch berücksichtigen dass andere mitgenommen werden
                if s.block == val.block then s.block = siteHistory[visitIdAufSID[v]].block
            val.block = siteHistory[visitIdAufSID[v]].block
          else
            if val.block == 0
              siteHistory[visitIdAufSID[v]].block = val.block = block #gibt nix zu erben man braucht einen neuen
              block++
            else
              siteHistory[visitIdAufSID[v]].block = val.block #gibt nix & man hat schon -> in die andere richtung vererben
        processed--
      if val.block is 0 or idToRef[id].length is 0
        val.block = block
        block++
      processed--
    if processed is 0
      for k,i of siteHistory
        logInfo([i.title.substr(0,40), i.sid, i.vid, i.ref, i.type, i.block])
  */


  storedBookmarks = {};

  storedContexts = {};

  bookMarks = {};

  folders = [];

  loadBookmarks = function(callbackFn) {
    storedBookmarks = {};
    storedContexts = {};
    bookMarks = {};
    folders = [];
    chrome.storage.local.get("storedBookmarks", function(bookmarks) {
      if (bookmarks.storedBookmarks) {
        return storedBookmarks = bookmarks.storedBookmarks;
      }
    });
    return chrome.storage.local.get("storedContexts", function(contexts) {
      if (contexts.storedContexts) {
        storedContexts = contexts.storedContexts;
      }
      return renderTaskMenu(callbackFn);
    });
  };

  renderTaskMenu = function(callbackFn) {
    var context_div, counter, head;

    context_div = $("<div>");
    context_div.addClass("bcontext");
    context_div.addClass("nocontext");
    head = $("<h2>");
    head.addClass("nocontext");
    head.text("kontextlos");
    context_div.append(head);
    $("#bookmarklist").append($(context_div));
    counter = 0;
    chrome.bookmarks.getTree(function(bookmarkTreeNodes) {
      var bm_div, bmtitle, bookmarkFolder, bookmarkFolderTitle, color, contextColor, favicon, initBookmarkFolder, m, o, title, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

      initBookmarkFolder = bookmarkTreeNodes[0].children[0].children;
      bookmarkFolderTitle = "";
      for (_i = 0, _len = initBookmarkFolder.length; _i < _len; _i++) {
        bookmarkFolder = initBookmarkFolder[_i];
        if (bookmarkFolder.title === "conmarks") {
          bookmarkFolderTitle = bookmarkFolder;
          _ref = bookmarkFolder.children;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            m = _ref[_j];
            contextColor = "9F0";
            if (!storedContexts[m.title]) {
              storedContexts[m.title] = {
                color: contextColor,
                active: true
              };
            } else {
              contextColor = storedContexts[m.title].color;
            }
            folders.push(m.title);
            context_div = $("<div>");
            context_div.addClass("bcontext");
            context_div.addClass(m.title);
            head = $("<div>");
            head.css("background", contextColor);
            head.addClass(m.title);
            title = $("<h2>");
            title.css("background", contextColor);
            title.addClass(m.title);
            title.text(m.title);
            color = $("<input>");
            color.attr("id", m.title);
            color.attr("name", m.title);
            color.attr("type", "text");
            color.attr("value", contextColor);
            head.append(color);
            head.append(title);
            context_div.append(head);
            color.colorPicker({
              onColorChange: function(id, newValue) {
                var $bcontent, $pheads, button, content, newhead, newhead2;

                newhead = ".bcontext." + id + " h2";
                newhead2 = ".bcontext ." + id;
                $(newhead).css("background", newValue);
                $(newhead2).css("background", newValue);
                button = "button." + id;
                content = "div.head." + id + ", div.content." + id + ".bookmark";
                $(button).css("background", newValue);
                $(content).css("background", newValue);
                $pheads = ".contextgroup." + id + " div.head";
                $($pheads).css("background", newValue);
                $bcontent = ".contextgroup." + id + " div.infocontent.bookmark";
                $($bcontent).css("background", newValue);
                storedContexts[id].color = newValue;
                chrome.storage.local.set({
                  "storedContexts": storedContexts
                });
                return null;
              }
            });
            $("#bookmarklist").append($(context_div));
            counter++;
            if (m.children != null) {
              _ref1 = m.children;
              for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                o = _ref1[_k];
                bookMarks[o.url] = {
                  context: m.title,
                  id: o.title,
                  bid: o.id
                };
                if (!storedBookmarks[o.url]) {
                  storedBookmarks[o.url] = {
                    bid: o.id,
                    visitTime: o.dateAdded
                  };
                }
                bm_div = $("<div>");
                bm_div.addClass("bookmark");
                favicon = $("<img>");
                favicon.attr({
                  src: "chrome://favicon/" + o.url
                });
                favicon.addClass("favic");
                bm_div.append($(favicon));
                bmtitle = $("<a>");
                bmtitle.attr("href", o.url);
                bmtitle.text(o.title);
                bm_div.append(bmtitle);
                context_div.append(bm_div);
              }
            } else {
              bookMarks[m.url] = {
                context: void 0,
                id: m.title,
                bid: m.id
              };
            }
          }
        }
        null;
      }
      if (!bookmarkFolderTitle) {
        chrome.bookmarks.create({
          'parentId': "1",
          'title': 'conmarks'
        }, function(bookmarkTreeNodes) {
          chrome.bookmarks.create({
            'parentId': bookmarkTreeNodes.id,
            'title': 'privat'
          }, function(bookmarkTreeNodes) {
            return null;
          });
          chrome.bookmarks.create({
            'parentId': bookmarkTreeNodes.id,
            'title': 'arbeit'
          }, function(bookmarkTreeNodes) {
            return null;
          });
          chrome.bookmarks.create({
            'parentId': bookmarkTreeNodes.id,
            'title': 'uni'
          }, function(bookmarkTreeNodes) {
            return null;
          });
          return null;
        });
      }
      context_div = $("<div>");
      context_div.addClass("bcontext");
      context_div.addClass("newcontext");
      head = $("<h2>");
      head.addClass("newcontext");
      head.text("+");
      context_div.append(head);
      $("#bookmarklist").append($(context_div));
      hideInactiveTasks();
      callbackFn();
      return null;
    });
    return null;
  };

  hideInactiveTasks = function() {
    var button, content, context, v, _results;

    _results = [];
    for (context in storedContexts) {
      v = storedContexts[context];
      if (jQuery.inArray(context, folders) < 0 && context !== "nocontext") {
        delete storedContexts[context];
        chrome.storage.local.set({
          "storedContexts": storedContexts
        });
      }
      button = "button." + context;
      content = "div.head." + context + ", div.content." + context + ".bookmark";
      $(button).css("background", v.color);
      $(content).css("background", v.color);
      if (!v.active) {
        _results.push(toggleActiveState(context));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  toggleActiveState = function(context) {
    var contextClass, toggleBookmark, toggleContext;

    toggleContext = ".bcontext." + context;
    $(toggleContext).toggleClass("contextactivestate");
    toggleBookmark = ".bcontext." + context + " .bookmark";
    $(toggleBookmark).toggle("fast");
    contextClass = "#historycontent ." + context;
    $(contextClass).toggle("fast");
    $(contextClass).css("display", "inline");
    if (!googlevisible) {
      contextClass = "#historycontent ." + context + ".googleblock";
      $(contextClass).toggle("fast");
      $(contextClass).css("display", "inline");
    }
    return null;
  };

  bookmarkIt = function(site, button) {
    var context, url;

    context = button.attr("class");
    url = site.url;
    if (bookMarks[url] != null) {
      if (bookMarks[url].context === context) {
        chrome.bookmarks.remove(storedBookmarks[url].bid, function() {
          delete storedBookmarks[site.url];
          return reload();
        });
      } else if (bookMarks[url].context !== void 0) {
        chrome.bookmarks.remove(storedBookmarks[url].bid, function() {
          delete storedBookmarks[site.url];
          return createBookmark(site, context);
        });
      }
    } else {
      createBookmark(site, context);
    }
    return null;
  };

  createBookmark = function(site, context) {
    chrome.bookmarks.getTree(function(bookmarkTreeNodes) {
      var bookmarkfolder, contextfolder, folder, m, newtitle, sub, _i, _j, _len, _len1, _ref;

      folder = bookmarkTreeNodes[0].children[0].children;
      newtitle = "" + site.vid + "___" + site.title;
      bookmarkfolder = void 0;
      contextfolder = void 0;
      for (_i = 0, _len = folder.length; _i < _len; _i++) {
        sub = folder[_i];
        if (sub.title === "conmarks") {
          bookmarkfolder = sub;
        }
      }
      _ref = bookmarkfolder.children;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        m = _ref[_j];
        if (context === m.title) {
          contextfolder = m;
          chrome.bookmarks.create({
            parentId: m.id,
            title: site.title,
            url: site.url
          }, function(BookmarkTreeNode) {
            storedBookmarks[site.url] = {
              bid: BookmarkTreeNode.id,
              visitTime: site.time
            };
            return reload();
          });
        }
      }
      if (contextfolder === void 0) {
        return chrome.bookmarks.create({
          parentId: bookmarkfolder.id,
          title: context
        }, function(bookmarkTreeNodes) {
          storedContexts[context] = {
            color: "#fff".id
          };
          console.log(bookmarkTreeNodes);
          contextfolder = bookmarkTreeNodes;
          return chrome.bookmarks.create({
            parentId: contextfolder.id,
            title: site.title,
            url: site.url
          }, function() {
            return reload();
          });
        });
      }
    });
    return null;
  };

  null;

  specialise = function(site, divToGo) {
    var special, title, url;

    url = site.url;
    title = site.title;
    special = void 0;
    if ((((url.substr(-4)).toLowerCase() === ".gif") || (url.substr(-4)).toLowerCase() === ".jpg") || ((url.substr(-4)).toLowerCase() === ".png") || ((url.substr(-5)).toLowerCase() === ".jpeg")) {
      special = "image";
      title = url.split(/[/]+/).pop().replace(/[_,.,?,=,&]/g, " ");
    } else if ((((url.substr(-3)).toLowerCase() === "pdf") || (url.substr(-4)).toLowerCase() === ".txt") || ((url.substr(-4)).toLowerCase() === ".doc") || ((url.substr(-5)).toLowerCase() === ".docx") || ((url.substr(-3)).toLowerCase() === ".js")) {
      special = "document";
      title = url.split(/[/]+/).pop().replace(/[_,.,?,=,&]/g, " ");
    } else if ((/youtube/.test(url)) && (/watch/.test(url)) && !(/channel/.test(url)) && !(/user/.test(url)) && !(/www.google/.test(url))) {
      title = title.split("- YouTube")[0];
      if (v_max > 0) {
        url = "https://www.youtube.com/embed/" + url.split("v=")[1].split('=')[0].split('&')[0];
        special = "y_video";
        v_max--;
      }
    } else if (/Google-Suche/.test(title)) {
      special = "google";
    } else if (/mail.google.com/.test(url)) {
      special = "mail";
    }
    site.title = title;
    site.url = url;
    site.special = special;
    if (title === "") {
      special = "empty";
    } else {
      renderItem(site, divToGo);
    }
    return null;
  };

  thelastURL = "";

  thelastTitle = "";

  renderItem = function(item, divToGo) {
    var bid, content_div, favicon, head_div, info_div, inhalt, link, notabhead, panel_div, qtl, ref, relevance, sid, special, tabhead, title, ttl, type, url, utl, vid, videoframe;

    title = item.title;
    url = item.url;
    sid = item.sid;
    vid = item.vid;
    type = item.type;
    bid = item.bid;
    special = item.special;
    ref = item.ref;
    relevance = item.relevance;
    panel_div = $("<div>");
    if ((thelastURL.substr(0, thelastURL.length - 3)) === (url.substr(0, url.length - 3)) || thelastTitle === title) {
      panel_div.addClass("stacking");
    }
    thelastURL = url;
    thelastTitle = title;
    panel_div.addClass("panel");
    panel_div.addClass(type);
    panel_div.addClass(special);
    if (item.nav != null) {
      panel_div.addClass(item.nav);
    }
    if (ref === "0") {
      panel_div.addClass("refzero");
    }
    if (relevance > 20) {
      panel_div.addClass("rel_big");
    } else if (relevance > 5) {
      panel_div.addClass("rel_some");
    } else if (relevance >= 2) {
      panel_div.addClass("rel_twice");
    }
    content_div = $("<div>");
    content_div.addClass("content");
    head_div = $("<div>");
    head_div.addClass("head");
    info_div = $("<div>");
    info_div.addClass("infocontent");
    if (item.tab !== "") {
      tabhead = $("<div>");
      tabhead.addClass("tabbutton");
      panel_div.addClass("itsatab");
      tabhead.attr("tabid", item.tab);
      tabhead.on("click", function() {
        chrome.tabs.remove(item.tab);
        tabhead.removeClass("tabbutton");
        return panel_div.removeClass("itsatab");
      });
      info_div.click(function() {
        return chrome.tabs.get(item.tab, function(geTab) {
          return chrome.tabs.highlight({
            windowId: geTab.windowId,
            tabs: geTab.index
          }, function() {});
        });
      });
      panel_div.append($(tabhead));
    } else {
      notabhead = $("<div>");
      notabhead.addClass("notab");
      panel_div.append($(notabhead));
    }
    favicon = $("<img>");
    favicon.attr({
      src: "chrome://favicon/" + url
    });
    favicon.addClass("favicon");
    head_div.append($(favicon));
    head_div.attr("vid", item.vid);
    head_div.attr("url", item.url);
    head_div.attr("title", item.title);
    head_div.attr("time", item.time);
    if (item.bid !== void 0) {
      info_div.attr("bookmark", item.bid);
      info_div.addClass("bookmark");
      info_div.css("background", storedContexts[item.context].color);
    }
    link = $("<a>");
    inhalt = $("<p>");
    link.attr({
      href: url
    });
    link.addClass("urladress");
    if (filter.query !== "") {
      qtl = filter.query.toLowerCase();
      ttl = title.toLowerCase();
      utl = url.toLowerCase();
      if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) > 0) {
        panel_div.addClass("lessimportant");
      } else if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) < 0) {
        panel_div.addClass("unimportant");
      }
    }
    if (special === "image") {
      content_div.css("background", "url(" + url.substr(url.search(/http/)) + ") 50% 20% ");
    }
    if (special === "google") {
      title = title.split(" - Google-Suche")[0];
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    } else if (special === "y_video") {
      videoframe = $("<iframe>");
      videoframe.addClass("youtubevideo");
      videoframe.attr({
        src: url
      });
      info_div.append(videoframe);
    } else {
      inhalt.text(shortenTitle(title, url));
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    }
    info_div.append($(link));
    content_div.append(head_div);
    content_div.append(info_div);
    panel_div.append($(content_div));
    return divToGo.append($(panel_div));
  };

  shortenTitle = function(title, url) {
    var shorten;

    shorten = 40;
    title = title.split(" - ")[0];
    title = title.split(" – ")[0];
    title = title.length > shorten ? title.substr(0, shorten) + "..." : title;
    if (title === "") {
      title = url.substr(0, shorten) + "...";
    }
    return title;
  };

  addClearDiv = function(div) {
    var clear;

    clear = $("<div>");
    clear.addClass("clear");
    return div.append($(clear));
  };

  createButtons = function(head_div, special, item) {
    var button, c, del, v, _results;

    del = $("<button>");
    del.addClass("delete");
    del.attr("title", "delete");
    del.text("X");
    del.on("click", function() {
      return chrome.history.deleteUrl({
        url: item.url
      }, function() {
        return head_div.parent().parent().remove();
      });
    });
    head_div.append($(del));
    if (special !== "google" && special !== "empty") {
      _results = [];
      for (c in storedContexts) {
        v = storedContexts[c];
        if (c !== "nocontext") {
          button = $("<button>");
          button.css("background", v.color);
          button.addClass(c);
          button.attr("title", c);
          button.text("");
          button.on("click", function() {
            return bookmarkIt(item, $(this));
          });
          if (!storedContexts[c].active) {
            button.hide();
          }
          _results.push(head_div.append($(button)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  addDevInfo = function(div, a) {
    var i, info, _i, _len;

    for (_i = 0, _len = a.length; _i < _len; _i++) {
      i = a[_i];
      info = $("<p>");
      info.addClass("devinfo");
      info.text(i);
      div.append($(info));
    }
    return null;
  };

  v_max = 0;

  filter = {
    results: 50,
    time: 0,
    query: "",
    mode: "none"
  };

  min = 50;

  max = 2000;

  googlevisible = true;

  tabArray = {};

  $(document).ready(function() {
    chrome.storage.local.get("query", function(result) {
      if (result.query != null) {
        filter.query = result.query;
        return $("#search").val(result.query);
      }
    });
    $("#search").change(function() {
      filter.query = $('#search').val();
      $("#historycontent").empty();
      chrome.storage.local.set({
        "query": filter.query
      });
      return reload();
    });
    $("#bookmarklist").on("click", "h2", function() {
      var context;

      context = $(this).context.className.split(" ")[0];
      toggleActiveState(context);
      if (context === "nocontext" && (storedContexts[context] == null)) {
        storedContexts[context] = {
          active: true
        };
      }
      if (storedContexts[context].active) {
        storedContexts[context].active = false;
      } else {
        storedContexts[context].active = true;
      }
      chrome.storage.local.set({
        "storedContexts": storedContexts
      });
      return null;
    });
    $("#configbar").on("click", "#hidegoogle", function() {
      $(".googleblock").toggle("fast");
      return googlevisible = !googlevisible;
    });
    chrome.storage.local.get("hSlider", function(result) {
      var query_slider, xpos;

      xpos = 0;
      if (result.hSlider != null) {
        xpos = result.hSlider;
      } else {
        null;
      }
      query_slider = new Dragdealer('simple-slider', {
        x: result.hSlider,
        steps: max,
        callback: function(x) {
          filter.results = parseInt((max - min) * query_slider.value.current[0] + min);
          chrome.storage.local.set({
            "hSlider": x
          });
          return reload();
        },
        animationCallback: function(x) {
          return $("#handle_amount").text(parseInt((max - min) * x + min));
        }
      });
      filter.results = parseInt((max - min) * xpos + min);
      return start();
    });
    return null;
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === "complete") {
      if (tab.url !== "chrome://newtab/") {
        return reload();
      }
    }
  });

  createBlocks = function() {
    var $contextgroup, block, blocksToProcess, cblock, contextGroup, fblock, item, key, nocontextGroup, _i, _j, _k, _len, _len1, _len2;

    blocksToProcess = blocks.length;
    blocks.sort(function(a, b) {
      if (a.time <= b.time) {
        return 1;
      } else {
        return -1;
      }
    });
    for (_i = 0, _len = blocks.length; _i < _len; _i++) {
      block = blocks[_i];
      blocksToProcess--;
      if ((block != null) && !block.processed) {
        if (block.context === "") {
          nocontextGroup = $("<div>");
          nocontextGroup.addClass("contextgroup");
          nocontextGroup.addClass("group" + block.id);
          nocontextGroup.addClass("nocontext");
          if (block.google) {
            nocontextGroup.addClass("googleblock");
          }
          $("#historycontent").append($(nocontextGroup));
        } else {
          for (_j = 0, _len1 = blocks.length; _j < _len1; _j++) {
            cblock = blocks[_j];
            if ((cblock != null) && cblock.context === block.context) {
              contextGroup = $("<div>");
              contextGroup.addClass("contextgroup");
              contextGroup.addClass("group" + cblock.id);
              contextGroup.addClass(block.context);
              $("#historycontent").append($(contextGroup));
              cblock.processed = true;
              if (!storedContexts[block.context].active) {
                $(".group" + cblock.id).hide();
              }
            }
          }
        }
      }
      if (blocksToProcess === 1) {
        siteHistory.reverse();
        for (key in siteHistory) {
          item = siteHistory[key];
          $contextgroup = $(".group" + item.block);
          specialise(item, $contextgroup);
          for (_k = 0, _len2 = blocks.length; _k < _len2; _k++) {
            fblock = blocks[_k];
            if ((fblock != null) && item.block === fblock.id && fblock.context !== "") {
              $(".group" + item.block + " .panel .head").css("background", storedContexts[fblock.context].color);
            }
          }
        }
      }
    }
    if (!googlevisible) {
      $(".googleblock").toggle("fast");
    }
    if (!storedContexts["nocontext"].active) {
      $("#historycontent .nocontext").hide();
    }
    return $(".head").hover((function() {
      var sInfo;

      sInfo = {};
      sInfo.url = $(this).attr("url");
      sInfo.vid = $(this).attr("vid");
      sInfo.title = $(this).attr("title");
      sInfo.time = $(this).attr("time");
      createButtons($(this), "", sInfo);
      return addClearDiv($(this));
    }), function() {
      $(this).find("button").remove();
      return $(this).find(".clear").remove();
    });
  };

  createHistory = function() {
    chrome.tabs.query({}, function(tabs) {
      var i, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = tabs.length; _i < _len; _i++) {
        i = tabs[_i];
        _results.push(tabArray[i.url] = i.id);
      }
      return _results;
    });
    return loadHistory(createBlocks);
  };

  start = function() {
    return loadBookmarks(createHistory);
  };

  /*
  initSlider = (hSlider) ->
    query_slider = new Dragdealer 'simple-slider',
      x: hSlider, steps: max
      callback: (x) -> filter.results = parseInt (max-min)*query_slider.value.current[0]+min;  chrome.storage.local.set "hSlider":x; reload()
      animationCallback: (x) -> $("#handle_amount").text parseInt((max-min)*x+min)
  */


  reload = function() {
    $('#historycontent').empty();
    $('#bookmarklist').empty();
    $('.colorPicker-palette').remove();
    v_max = 10;
    tabArray = {};
    start();
    return null;
  };

}).call(this);
