// Generated by CoffeeScript 1.6.2
(function() {
  var addClearDiv, addDevInfo, createButtons, renderItem, shortenTitle, specialise, thelastTitle, thelastURL;

  specialise = function(site, divToGo) {
    var special, title, url;

    url = site.url;
    title = site.title;
    special = void 0;
    if ((((url.substr(-4)).toLowerCase() === ".gif") || (url.substr(-4)).toLowerCase() === ".jpg") || ((url.substr(-4)).toLowerCase() === ".png") || ((url.substr(-5)).toLowerCase() === ".jpeg")) {
      special = "image";
      title = url.split(/[/]+/).pop().replace(/[_,.,?,=,&]/g, " ");
    } else if ((((url.substr(-3)).toLowerCase() === "pdf") || (url.substr(-4)).toLowerCase() === ".txt") || ((url.substr(-4)).toLowerCase() === ".doc") || ((url.substr(-5)).toLowerCase() === ".docx") || ((url.substr(-3)).toLowerCase() === ".js")) {
      special = "document";
      title = url.split(/[/]+/).pop().replace(/[_,.,?,=,&]/g, " ");
    } else if ((/youtube/.test(url)) && (/watch/.test(url)) && !(/channel/.test(url)) && !(/user/.test(url)) && !(/www.google/.test(url))) {
      title = title.split("- YouTube")[0];
      if (v_max > 0) {
        url = "https://www.youtube.com/embed/" + url.split("v=")[1].split('=')[0].split('&')[0];
        special = "y_video";
        v_max--;
      }
    } else if (/Google-Suche/.test(title)) {
      special = "google";
    } else if (/mail.google.com/.test(url)) {
      special = "mail";
    }
    site.title = title;
    site.url = url;
    site.special = special;
    if (title === "") {
      special = "empty";
    } else {
      renderItem(site, divToGo);
    }
    return null;
  };

  thelastURL = "";

  thelastTitle = "";

  renderItem = function(item, divToGo) {
    var bid, content_div, favicon, head_div, info_div, inhalt, link, notabhead, panel_div, qtl, ref, relevance, sid, special, tabhead, title, ttl, type, url, utl, vid, videoframe;

    title = item.title;
    url = item.url;
    sid = item.sid;
    vid = item.vid;
    type = item.type;
    bid = item.bid;
    special = item.special;
    ref = item.ref;
    relevance = item.relevance;
    panel_div = $("<div>");
    if ((thelastURL.substr(0, thelastURL.length - 3)) === (url.substr(0, url.length - 3)) || thelastTitle === title) {
      panel_div.addClass("stacking");
    }
    thelastURL = url;
    thelastTitle = title;
    panel_div.addClass("panel");
    panel_div.addClass(type);
    panel_div.addClass(special);
    if (item.nav != null) {
      panel_div.addClass(item.nav);
    }
    if (ref === "0") {
      panel_div.addClass("refzero");
    }
    if (relevance > 20) {
      panel_div.addClass("rel_big");
    } else if (relevance > 5) {
      panel_div.addClass("rel_some");
    } else if (relevance >= 2) {
      panel_div.addClass("rel_twice");
    }
    content_div = $("<div>");
    content_div.addClass("content");
    head_div = $("<div>");
    head_div.addClass("head");
    info_div = $("<div>");
    info_div.addClass("infocontent");
    if (item.tab !== "") {
      tabhead = $("<div>");
      tabhead.addClass("tabbutton");
      panel_div.addClass("itsatab");
      tabhead.attr("tabid", item.tab);
      tabhead.on("click", function() {
        chrome.tabs.remove(item.tab);
        tabhead.removeClass("tabbutton");
        return panel_div.removeClass("itsatab");
      });
      info_div.click(function() {
        return chrome.tabs.get(item.tab, function(geTab) {
          return chrome.tabs.highlight({
            windowId: geTab.windowId,
            tabs: geTab.index
          }, function() {});
        });
      });
      panel_div.append($(tabhead));
    } else {
      notabhead = $("<div>");
      notabhead.addClass("notab");
      panel_div.append($(notabhead));
    }
    favicon = $("<img>");
    favicon.attr({
      src: "chrome://favicon/" + url
    });
    favicon.addClass("favicon");
    head_div.append($(favicon));
    head_div.attr("vid", item.vid);
    head_div.attr("url", item.url);
    head_div.attr("title", item.title);
    head_div.attr("time", item.time);
    if (item.bid !== void 0) {
      info_div.attr("bookmark", item.bid);
      info_div.addClass("bookmark");
      info_div.css("background", storedContexts[item.context].color);
    }
    link = $("<a>");
    inhalt = $("<p>");
    link.attr({
      href: url
    });
    link.addClass("urladress");
    if (filter.query !== "") {
      qtl = filter.query.toLowerCase();
      ttl = title.toLowerCase();
      utl = url.toLowerCase();
      if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) > 0) {
        panel_div.addClass("lessimportant");
      } else if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) < 0) {
        panel_div.addClass("unimportant");
      }
    }
    if (special === "image") {
      content_div.css("background", "url(" + url.substr(url.search(/http/)) + ") 50% 20% ");
    }
    if (special === "google") {
      title = title.split(" - Google-Suche")[0];
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    } else if (special === "y_video") {
      videoframe = $("<iframe>");
      videoframe.addClass("youtubevideo");
      videoframe.attr({
        src: url
      });
      info_div.append(videoframe);
    } else {
      inhalt.text(shortenTitle(title, url));
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    }
    info_div.append($(link));
    content_div.append(head_div);
    content_div.append(info_div);
    panel_div.append($(content_div));
    return divToGo.append($(panel_div));
  };

  shortenTitle = function(title, url) {
    var shorten;

    shorten = 40;
    title = title.split(" - ")[0];
    title = title.split(" – ")[0];
    title = title.length > shorten ? title.substr(0, shorten) + "..." : title;
    if (title === "") {
      title = url.substr(0, shorten) + "...";
    }
    return title;
  };

  addClearDiv = function(div) {
    var clear;

    clear = $("<div>");
    clear.addClass("clear");
    return div.append($(clear));
  };

  createButtons = function(head_div, special, item) {
    var button, c, del, v, _results;

    del = $("<button>");
    del.addClass("delete");
    del.attr("title", "delete");
    del.text("X");
    del.on("click", function() {
      return chrome.history.deleteUrl({
        url: item.url
      }, function() {
        return head_div.parent().parent().remove();
      });
    });
    head_div.append($(del));
    if (special !== "google" && special !== "empty") {
      _results = [];
      for (c in storedContexts) {
        v = storedContexts[c];
        if (c !== "nocontext") {
          button = $("<button>");
          button.css("background", v.color);
          button.addClass(c);
          button.attr("title", c);
          button.text("");
          button.on("click", function() {
            return bookmarkIt(item, $(this));
          });
          if (!storedContexts[c].active) {
            button.hide();
          }
          _results.push(head_div.append($(button)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  addDevInfo = function(div, a) {
    var i, info, _i, _len;

    for (_i = 0, _len = a.length; _i < _len; _i++) {
      i = a[_i];
      info = $("<p>");
      info.addClass("devinfo");
      info.text(i);
      div.append($(info));
    }
    return null;
  };

}).call(this);
