// Generated by CoffeeScript 1.6.2
(function() {
  var bmarks, filter, initSlider, phistory, reload, v_max;

  v_max = 0;

  filter = {
    results: 40,
    time: 0,
    query: "",
    mode: "none"
  };

  bmarks = 0;

  phistory = 0;

  $(document).ready(function() {
    chrome.storage.local.get("query", function(result) {
      if (result.query != null) {
        filter.query = result.query;
        return $("#search").val(result.query);
      }
    });
    chrome.storage.local.get("hSlider", function(result) {
      if (result.hSlider != null) {
        return initSlider(result.hSlider);
      } else {
        return initSlider(0);
      }
    });
    $("#search").change(function() {
      filter.query = $('#search').val();
      $("#historycontent").empty();
      chrome.storage.local.set({
        "query": filter.query
      });
      return reload();
    });
    bmarks = new hv.Bookmarks();
    phistory = new hv.ProcessHistory(filter);
    bmarks.loadBookmarks();
    try {
      phistory.loadHistory();
    } finally {
      console.log(phistory.getHistory());
    }
    return null;
  });

  reload = function() {
    var blockId, blockStyle, blocks, bookMarks, siteHistory, visitId_pointo_SiteId;

    chrome.storage.local.set({
      "storedBookmarks": storedBookmarks
    });
    $('#historycontent').empty();
    $('#bookmarklist').empty();
    v_max = 0;
    siteHistory = [];
    bookMarks = {};
    blockId = 0;
    blocks = {};
    visitId_pointo_SiteId = [];
    return blockStyle = [];
  };

  initSlider = function(hSlider) {
    var max, min, query_slider;

    min = 50;
    max = 500;
    return query_slider = new Dragdealer('simple-slider', {
      x: hSlider,
      steps: max,
      callback: function(x) {
        filter.results = parseInt((max - min) * query_slider.value.current[0] + min);
        chrome.storage.local.set({
          "hSlider": x
        });
        return reload();
      },
      animationCallback: function(x) {
        return $("#handle_amount").text(parseInt((max - min) * x + min));
      }
    });
  };

}).call(this);
