// Generated by CoffeeScript 1.6.2
(function() {
  var addClearDiv, addDevInfo, createButtons, renderItem, specialise;

  specialise = function(site, divToGo) {
    var context, shorten, special, title, url;

    url = site.url;
    title = site.title;
    context = void 0;
    special = void 0;
    if (((url.substr(-4)) === ".jpg") || ((url.substr(-4)) === ".png") || ((url.substr(-5)) === ".jpeg")) {
      special = "image";
      title = "Abbildung";
    } else if ((/youtube/.test(url)) && (/watch/.test(url))) {
      title = title.split("- YouTube")[0];
      if (v_max > 0) {
        url = "https://www.youtube.com/embed/" + url.split("v=")[1].split('=')[0].split('&')[0];
        special = "video";
        v_max--;
      }
    } else if (/Google-Suche/.test(title)) {
      special = "google";
    } else if (/mail.google.com/.test(url)) {
      special = "mail";
    }
    title = title.split(" - ")[0];
    title = title.split(" – ")[0];
    shorten = 20;
    title = title.length > shorten ? title.substr(0, shorten) + "..." : title;
    site.url = url;
    site.title = title;
    site.special = special;
    if (title === "") {
      special = "empty";
      site.title = url;
    } else {
      renderItem(site, divToGo);
    }
    return null;
  };

  renderItem = function(item, divToGo) {
    var bid, content_div, context, favicon, head_div, inhalt, link, notabhead, panel_div, pic, qtl, ref, relevance, sid, special, tabhead, title, ttl, type, url, utl, vid, videoframe;

    title = item.title;
    url = item.url;
    sid = item.sid;
    vid = item.vid;
    type = item.type;
    bid = item.bid;
    special = item.special;
    ref = item.ref;
    relevance = item.relevance;
    panel_div = $("<div>");
    panel_div.addClass("panel");
    panel_div.addClass(type);
    if (item.nav != null) {
      panel_div.addClass(item.nav);
    }
    if (ref === "0") {
      panel_div.addClass("refzero");
    }
    if (relevance > 20) {
      panel_div.addClass("rel_big");
    } else if (relevance > 5) {
      panel_div.addClass("rel_some");
    } else if (relevance >= 2) {
      panel_div.addClass("rel_twice");
    }
    panel_div.addClass(special);
    head_div = $("<div>");
    content_div = $("<div>");
    content_div.addClass("content");
    head_div.addClass("head");
    if (item.tab !== "") {
      tabhead = $("<div>");
      tabhead.addClass("tabbutton");
      tabhead.attr("tabid", item.tab);
      tabhead.on("click", function() {
        return chrome.tabs.remove(item.tab);
      });
      panel_div.addClass("itsatab");
      panel_div.append($(tabhead));
    } else {
      notabhead = $("<div>");
      notabhead.addClass("notab");
      panel_div.append($(notabhead));
    }
    favicon = $("<img>");
    favicon.attr({
      src: "chrome://favicon/" + url
    });
    favicon.addClass("favicon");
    head_div.append($(favicon));
    createButtons(head_div, special, item);
    addClearDiv(head_div);
    if (blockStyle[blocks[item.sid]] != null) {
      context = blockStyle[blocks[item.sid]];
      head_div.addClass(context);
      panel_div.addClass(context);
    } else {
      panel_div.addClass("nocontext");
    }
    if (item.bookmark !== void 0) {
      context += " bookmark";
      content_div.addClass(context + " bookmark");
    }
    link = $("<a>");
    inhalt = $("<p>");
    link.attr({
      href: url
    });
    link.addClass("urladress");
    if (filter.query !== "") {
      qtl = filter.query.toLowerCase();
      ttl = title.toLowerCase();
      utl = url.toLowerCase();
      if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) > 0) {
        panel_div.addClass("lessimportant");
      } else if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) < 0) {
        panel_div.addClass("unimportant");
      }
    }
    if (special === "image") {
      pic = $("<img>");
      pic.attr({
        src: url.substr(url.search(/http/))
      });
      pic.addClass("imgpreview");
      inhalt.append(pic);
      link.append($(inhalt));
    } else if (special === "google") {
      title = title.split(" - Google-Suche")[0];
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    } else if (special === "video") {
      videoframe = $("<iframe>");
      videoframe.addClass("youtubevideo");
      videoframe.attr({
        src: url
      });
      content_div.append(videoframe);
    } else {
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    }
    content_div.append($(link));
    panel_div.append(head_div);
    panel_div.append($(content_div));
    return divToGo.append($(panel_div));
  };

  addClearDiv = function(div) {
    var clear;

    clear = $("<div>");
    clear.addClass("clear");
    return div.append($(clear));
  };

  createButtons = function(head_div, special, item) {
    var button, c, v, _results;

    if (special !== "google" && special !== "empty") {
      _results = [];
      for (c in storedContexts) {
        v = storedContexts[c];
        button = $("<button>");
        button.css("background", v.color);
        button.addClass(c);
        button.text("");
        button.on("click", function() {
          return bookmarkIt(item, c);
        });
        if (!storedContexts[c].active) {
          button.hide();
        }
        _results.push(head_div.append($(button)));
      }
      return _results;
    }
  };

  addDevInfo = function(div, a) {
    var i, info, _i, _len;

    for (_i = 0, _len = a.length; _i < _len; _i++) {
      i = a[_i];
      info = $("<p>");
      info.addClass("devinfo");
      info.text(i);
      div.append($(info));
    }
    return null;
  };

}).call(this);
