// Generated by CoffeeScript 1.6.1
(function() {
  var connections, lastPage, setTabConnection;

  lastPage = "";

  connections = [];

  chrome.storage.local.get("connections", function(result) {
    if (result.connections != null) {
      return connections = result.connections;
    }
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === "complete") {
      console.log(tab);
      return setTabConnection(tab.url, tab.openerTabId);
    }
  });

  setTabConnection = function(orgTabUrl, referrerTabId) {
    if (typeof referrerTabId !== "undefined") {
      return chrome.tabs.get(referrerTabId, function(tab) {
        if (tab.url !== "chrome://newtab/" && orgTabUrl !== "chrome://newtab/") {
          connections.push({
            url: orgTabUrl,
            refurl: tab.url,
            nav: "tab"
          });
          chrome.storage.local.set({
            "connections": connections
          });
        }
        return lastPage = tab.url;
      });
    }
  };

  chrome.webNavigation.onCommitted.addListener(function(details) {
    if (details.transitionQualifiers) {
      if (details.transitionQualifiers === "forward_back") {
        return lastPage = details.url;
      }
    }
  });

  /* Query for getting all Tabs at once
  chrome.tabs.query {}, (Tabs) ->
    console.log Tabs
  
  # synchronise Storage of Tabinfo
  syncTabs = ->
    chrome.storage.local.set "tabs":tabArray
  
  chrome.webNavigation.onBeforeNavigate.addListener (details) ->
    console.log details
  */


}).call(this);
