// Generated by CoffeeScript 1.6.1
(function() {
  var connections, lastPage, setTabConnection, syncConnectedTabs, syncTabs, tabArray;

  lastPage = "";

  tabArray = [];

  connections = [];

  chrome.storage.local.get("connections", function(result) {
    if (result.connections != null) {
      return connections = result.connections;
    }
  });

  chrome.tabs.onCreated.addListener(function(tab) {
    tabArray[tab.id] = {
      url: tab.url,
      index: tab.index,
      windowId: tab.windowId,
      openerTabId: tab.openerTabId,
      highlighted: tab.highlighted,
      active: tab.active,
      pinned: tab.pinned,
      title: tab.title,
      incognito: tab.incognito
    };
    syncTabs();
    return setTabConnection(tab.url, tab.openerTabId);
  });

  setTabConnection = function(orgTabUrl, referrerTabId) {
    if (typeof referrerTabId !== "undefined") {
      return chrome.tabs.get(referrerTabId, function(tab) {
        if (tab.url !== "chrome://newtab/") {
          connections.push({
            url: orgTabUrl,
            refurl: tab.url,
            nav: "tab"
          });
          syncConnectedTabs();
        }
        return lastPage = tab.url;
      });
    }
  };

  syncTabs = function() {
    return chrome.storage.local.set({
      "tabs": tabArray
    });
  };

  syncConnectedTabs = function() {
    return chrome.storage.local.set({
      "connections": connections
    });
  };

  chrome.webNavigation.onCommitted.addListener(function(details) {
    console.log(details);
    if (details.transitionQualifiers) {
      if (details.transitionQualifiers === "forward_back") {
        connections.push({
          url: details.url,
          refurl: lastPage,
          nav: "forward_back"
        });
        console.log("fb");
        return lastPage = details.url;
      }
    }
  });

  /* Query for getting all Tabs at once
  chrome.tabs.query {}, (Tabs) ->
    console.log Tabs
  */


}).call(this);
