// Generated by CoffeeScript 1.6.1
var bookmark;

bookmark = function(c_panel, bid, vid, url, title, context) {
  var preclass;
  preclass = c_panel.attr("class");
  c_panel.removeClass();
  if (preclass === "") {
    preclass = void 0;
  }
  if (preclass != null) {
    chrome.bookmarks.remove(preclass.split(" ")[1], null);
  }
  if (preclass === void 0 || ((preclass != null) && preclass.split(" ")[0] !== context)) {
    chrome.bookmarks.getTree(function(bookmarkTreeNodes) {
      var m, morebms, n, newtitle, _i, _len, _results;
      morebms = bookmarkTreeNodes[0].children[1].children;
      newtitle = "" + vid + "___" + title;
      _results = [];
      for (_i = 0, _len = morebms.length; _i < _len; _i++) {
        n = morebms[_i];
        if (n.title === "conmarks") {
          if (context === void 0) {
            _results.push(chrome.bookmarks.create({
              parentId: n.id,
              title: newtitle,
              url: url
            }));
          } else {
            _results.push((function() {
              var _j, _len1, _ref, _results1;
              _ref = n.children;
              _results1 = [];
              for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                m = _ref[_j];
                if (context === m.title) {
                  _results1.push(chrome.bookmarks.create({
                    parentId: m.id,
                    title: newtitle,
                    url: url
                  }));
                } else {
                  _results1.push(void 0);
                }
              }
              return _results1;
            })());
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    c_panel.addClass(context);
    return chrome.bookmarks.getRecent(1, function(bookmarkTreeNodes) {
      c_panel.addClass(bookmarkTreeNodes[0].id);
      return console.log("neu" + bookmarkTreeNodes[0].id);
    });
  }
};

/* 
getBookmarks = () ->
  chrome.bookmarks.getTree (bookmarkTreeNodes) ->
    morebms = bookmarkTreeNodes[0].children[1].children;
    gotit = false
    for n in morebms
     if n.title is "conmarks" then gotit = true; return n
    if gotit is false then chrome.bookmarks.create {parentId:"2", title:"conmarks"}
*/

