// Generated by CoffeeScript 1.6.1
(function() {
  var blockId, blockStyle, blocks, bookMarks, bookmarkIt, bookmartise, context, createBookmark, filter, findOutlater, hSlider, loadBookmarks, loadHistory, processTabConnections, processVisitItems, processed, refArray, refMissing, refToBlock, reload, renderItem, shortUrls, siteContext, siteHistory, siteNetwork, specialise, tabconnections, urltoSid, v_max, visitIdArray;

  v_max = 0;

  filter = {
    results: 50,
    time: 0,
    query: "",
    mode: "none"
  };

  context = "empty";

  hSlider = 0;

  processed = 0;

  bookMarks = {};

  siteHistory = [];

  tabconnections = [];

  siteNetwork = [];

  siteContext = [];

  visitIdArray = {};

  refArray = [];

  blockId = 0;

  blocks = {};

  refToBlock = [];

  blockStyle = [];

  refMissing = [];

  urltoSid = {};

  findOutlater = [];

  shortUrls = [];

  $(document).ready(function() {
    var max, min, query_slider;
    chrome.storage.local.get("query", function(result) {
      if (result.query != null) {
        filter.query = result.query;
        return $("#search").val(result.query);
      }
    });
    chrome.storage.local.get("hSlider", function(result) {
      if (result.hSlider != null) {
        return query_slider.x = result.hSlider;
      }
    });
    min = 50;
    max = 500;
    query_slider = new Dragdealer('simple-slider', {
      x: hSlider,
      steps: max,
      callback: function(x, y) {
        filter.results = parseInt((max - min) * query_slider.value.current[0] + min);
        chrome.storage.local.set({
          "hSlider": x
        });
        return reload();
      },
      animationCallback: function(x, y) {
        return $("#handle_amount").text(parseInt((max - min) * x + min));
      }
    });
    $("#search").change(function() {
      filter.query = $('#search').val();
      $("#historycontent").empty();
      chrome.storage.local.set({
        "query": filter.query
      });
      return reload();
    });
    chrome.storage.local.get("connections", function(result) {
      if (result.connections != null) {
        tabconnections = result.connections;
      } else {
        tabconnections = [];
      }
      return loadBookmarks();
    });
    return null;
  });

  reload = function() {
    $('#historycontent').empty();
    siteHistory = [];
    bookMarks = {};
    loadBookmarks();
    visitIdArray = [];
    siteContext = [];
    v_max = 0;
    blocks = {};
    refToBlock = [];
    blockStyle = [];
    blockId = 0;
    refMissing = [];
    urltoSid = {};
    findOutlater = [];
    return shortUrls = [];
  };

  loadBookmarks = function() {
    var todo;
    todo = 0;
    chrome.bookmarks.getTree(function(bookmarkTreeNodes) {
      var bfolder, m, morebms, n, o, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
      bfolder = "";
      morebms = bookmarkTreeNodes[0].children[1].children;
      for (_i = 0, _len = morebms.length; _i < _len; _i++) {
        n = morebms[_i];
        if (n.title === "conmarks") {
          console.log("found");
          bfolder = n.title;
          _ref = n.children;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            m = _ref[_j];
            todo++;
            if (m.children != null) {
              _ref1 = m.children;
              for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                o = _ref1[_k];
                bookMarks[o.url] = {
                  context: m.title,
                  id: o.title.split("___", 1)[0],
                  bid: o.id
                };
              }
              todo--;
            } else {
              bookMarks[m.url] = {
                context: void 0,
                id: m.title.split("___", 1)[0],
                bid: m.id
              };
              todo--;
            }
          }
        }
      }
      if (!bfolder) {
        return chrome.bookmarks.create({
          'parentId': "2",
          'title': 'conmarks'
        }, function(bookmarkTreeNodes) {
          return null;
        });
      }
    });
    if (todo === 0) {
      loadHistory();
    }
    return null;
  };

  loadHistory = function() {
    var date, daydate, endtime, microsecondsPerDay, mode, starttime, time;
    time = filter.time;
    mode = filter.mode;
    processed = 0;
    date = new Date();
    daydate = date.getTime() - ((((date.getHours() + 1) * 60 + date.getMinutes()) * 60 + date.getSeconds()) * 1000);
    microsecondsPerDay = 1000 * 60 * 60 * 24;
    endtime = daydate - (microsecondsPerDay * (time - 1));
    starttime = daydate - (microsecondsPerDay * (30 + time));
    chrome.history.search({
      text: filter.query,
      maxResults: filter.results,
      startTime: starttime,
      endTime: endtime
    }, function(historyItems) {
      historyItems.forEach(function(site) {
        processed++;
        return chrome.history.getVisits({
          url: site.url
        }, function(visitItems) {
          return processVisitItems(site, visitItems);
        });
      });
      return null;
    });
    return null;
  };

  processVisitItems = function(site, visitItems) {
    var SiteItem, blockofreferredsid, i, id, noblockreferred, ref, referrer, relevance, type, vid, visits, _i, _len;
    id = site.id;
    vid = visitItems[visitItems.length - 1].visitId;
    type = visitItems[visitItems.length - 1].transition;
    ref = visitItems[visitItems.length - 1].referringVisitId;
    relevance = visitItems.length;
    /*----------------------------------------------------------------------------------------
    */

    visits = [];
    referrer = [];
    noblockreferred = true;
    blockofreferredsid = 0;
    for (_i = 0, _len = visitItems.length; _i < _len; _i++) {
      i = visitItems[_i];
      visits.push(i.visitId);
      if (i.referringVisitId !== "0") {
        referrer.push(i.referringVisitId);
      }
      visitIdArray[i.visitId] = {
        sid: id,
        ref: i.referringVisitId,
        vid: i.visitId
      };
      if ((refToBlock[i.referringVisitId] != null) && i.referringVisitId !== "0") {
        findOutlater[refToBlock[i.referringVisitId]] = i.referringVisitId;
      }
      refToBlock[i.referringVisitId] = id;
      if (refToBlock[i.visitId] != null) {
        noblockreferred = false;
        blockofreferredsid = refToBlock[i.visitId];
      }
    }
    siteNetwork[id] = {
      visits: visits,
      referrer: referrer
    };
    /*----------------------------------------------------------------------------------------
    */

    /*
    doit = true
    shortUrl = site.url.split("#")[0]
    #console.log shortUrl
    testArray = $.inArray shortUrl, shortUrls 
    if (testArray is -1)
      shortUrls.push shortUrl
    else #if referrer.length is 0 #&& site.url.split("#")[1]?
      #null
      #doit = false
    */

    /*
    if referrer.length is 0 && site.url.split("#")[1]?
      #shortUrl = site.url.split("#")[0]
      shortUrl = site.url.split("#")[0]
      testArray = $.inArray shortUrl, shortUrls
      if (testArray is -1)
        shortUrls.push shortUrl
        console.log site.url
      else
        doit = false
        #console.log site.url
    */

    if (referrer.length === 0) {
      refMissing[id] = site.url;
    }
    if (noblockreferred) {
      blocks[id] = blockId;
      blockId++;
    } else {
      blocks[id] = blocks[blockofreferredsid];
    }
    urltoSid[site.url] = id;
    SiteItem = {
      sid: site.id,
      vid: vid,
      url: site.url,
      title: site.title,
      type: type,
      ref: ref,
      relevance: relevance
    };
    siteHistory[id] = SiteItem;
    processed--;
    if (processed === 0) {
      return processTabConnections();
    }
  };

  processTabConnections = function() {
    var id, item, key, kk, newblockindex, oldblockindex, processIt, ref_id, referrer, rid, sid, tc, v_url, val, _i, _j, _len, _len1, _ref;
    processIt = 0;
    for (_i = 0, _len = tabconnections.length; _i < _len; _i++) {
      tc = tabconnections[_i];
      processIt++;
      for (sid in refMissing) {
        v_url = refMissing[sid];
        if (v_url === tc.url) {
          ref_id = urltoSid[tc.refurl];
          siteHistory[sid].nav = tc.nav;
          if (ref_id !== void 0) {
            oldblockindex = blocks[sid];
            newblockindex = blocks[ref_id];
            blocks[sid] = newblockindex;
            for (kk in blocks) {
              val = blocks[kk];
              if (val === oldblockindex) {
                blocks[kk] = newblockindex;
              }
            }
          }
        }
      }
      processIt--;
    }
    for (key in findOutlater) {
      val = findOutlater[key];
      if (val !== "0") {
        oldblockindex = blocks[key];
        newblockindex = blocks[refToBlock[val]];
        blocks[key] = newblockindex;
        for (kk in blocks) {
          val = blocks[kk];
          if (val === oldblockindex) {
            blocks[kk] = newblockindex;
          }
        }
      }
    }
    referrer = [];
    referrer[666] = "chrome://newtab/";
    _ref = tabconnections.reverse();
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      tc = _ref[_j];
      id = 0;
      rid = tc.refurl;
      for (key in siteHistory) {
        item = siteHistory[key];
        if (item.url === tc.refurl) {
          rid = item.vid;
        }
        if (item.url === tc.url) {
          id = item.vid;
        }
      }
    }
    for (key in siteHistory) {
      item = siteHistory[key];
      item.block = blocks[key];
      if (item.ref === "0" && referrer[item.vid]) {
        null;
      }
    }
    for (key in visitIdArray) {
      item = visitIdArray[key];
      processIt++;
      if (visitIdArray[item.ref] != null) {
        item.sidref = visitIdArray[item.ref].sid;
        siteHistory[item.sid].sidref = visitIdArray[item.ref].sid;
      }
      if (item.ref === "0" && referrer[item.vid]) {
        null;
      }
      processIt--;
    }
    return bookmartise();
  };

  bookmartise = function() {
    var bookmark, bprocessed, doit, item, key, shortUrl, testArray, val, _ref, _results;
    bprocessed = 0;
    for (key in siteHistory) {
      val = siteHistory[key];
      bprocessed++;
      bookmark = bookMarks[val.url] != null ? (bookMarks[val.url].bid, val.bookmark = true, blockStyle[blocks[key]] = bookMarks[val.url].context) : void 0;
    }
    if (bprocessed = filter.results) {
      siteHistory.sort(function(a, b) {
        if (a.vid >= b.vid) {
          return 1;
        } else {
          return -1;
        }
      });
      _ref = siteHistory.reverse();
      _results = [];
      for (key in _ref) {
        item = _ref[key];
        doit = true;
        shortUrl = item.url.split("#")[0];
        testArray = $.inArray(shortUrl, shortUrls);
        if (testArray === -1) {
          shortUrls.push(shortUrl);
          _results.push(specialise(item));
        } else {

        }
      }
      return _results;
    }
  };

  specialise = function(site) {
    var shorten, special, title, url;
    url = site.url;
    title = site.title;
    context = void 0;
    special = void 0;
    if (title === "") {
      special = "empty";
      title = url;
    } else {
      if (((url.substr(-4)) === ".jpg") || ((url.substr(-4)) === ".png") || ((url.substr(-5)) === ".jpeg")) {
        special = "image";
        title = "Abbildung";
      } else if ((/youtube/.test(url)) && (/watch/.test(url))) {
        title = title.split("- YouTube")[0];
        if (v_max > 0) {
          url = "https://www.youtube.com/embed/" + url.split("v=")[1].split('=')[0].split('&')[0];
          special = "video";
          v_max--;
        }
      } else if (/Google-Suche/.test(title)) {
        special = "google";
      } else if (/mail.google.com/.test(url)) {
        special = "mail";
      }
    }
    title = title.split(" - ")[0];
    shorten = 40;
    title = title.length > shorten ? title.substr(0, shorten) + "..." : title;
    site.url = url;
    site.title = title;
    site.special = special;
    return renderItem(site);
  };

  renderItem = function(item) {
    var bid, button, button2, button3, clear, content_div, favicon, head_div, info, info1, info2, inhalt, link, panel_div, pic, qtl, ref, relevance, sid, special, title, ttl, type, url, utl, vid, videoframe;
    title = item.title;
    url = item.url;
    sid = item.sid;
    vid = item.vid;
    type = item.type;
    bid = item.bid;
    special = item.special;
    ref = item.ref;
    relevance = item.relevance;
    panel_div = $("<div>");
    panel_div.addClass("panel");
    panel_div.addClass(type);
    if (item.nav != null) {
      panel_div.addClass(item.nav);
    }
    if (ref === "0") {
      panel_div.addClass("refzero");
    }
    if (relevance > 20) {
      panel_div.addClass("rel_big");
    } else if (relevance > 5) {
      panel_div.addClass("rel_some");
    } else if (relevance >= 2) {
      panel_div.addClass("rel_twice");
    }
    head_div = $("<div>");
    content_div = $("<div>");
    head_div.addClass("head");
    favicon = $("<img>");
    favicon.attr({
      src: "chrome://favicon/" + url
    });
    favicon.addClass("favicon");
    head_div.append($(favicon));
    if (special !== "google" && special !== "empty") {
      button = $("<button>");
      button.text("1");
      button.click(function() {
        return bookmarkIt(item, "first");
      });
      button2 = $("<button>");
      button2.text("2");
      button2.click(function() {
        return bookmarkIt(item, "second");
      });
      button3 = $("<button>");
      button3.text("3");
      button3.click(function() {
        return bookmarkIt(item, "third");
      });
      head_div.append($(button3));
      head_div.append($(button2));
      head_div.append($(button));
    }
    clear = $("<div>");
    clear.addClass("clear");
    head_div.append($(clear));
    if (blockStyle[blocks[item.sid]] != null) {
      context = blockStyle[blocks[item.sid]];
      head_div.addClass(context);
    }
    if (item.bookmark !== void 0) {
      item.context += " bookmark";
      content_div.addClass(context);
    }
    link = $("<a>");
    inhalt = $("<p>");
    link.attr({
      href: url
    });
    link.addClass("urladress");
    if (filter.query !== "") {
      qtl = filter.query.toLowerCase();
      ttl = title.toLowerCase();
      utl = url.toLowerCase();
      if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) > 0) {
        panel_div.addClass("lessimportant");
      } else if (ttl.indexOf(qtl) < 0 && utl.indexOf(qtl) < 0) {
        panel_div.addClass("unimportant");
      }
    }
    if (special === "image") {
      pic = $("<img>");
      pic.attr({
        src: url.substr(url.search(/http/))
      });
      pic.addClass("imgpreview");
      inhalt.append(pic);
      link.append($(inhalt));
    }
    if (special === "google") {
      title = title.split(" - Google-Suche")[0];
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    }
    if (special === "video") {
      videoframe = $("<iframe>");
      videoframe.addClass("youtubevideo");
      videoframe.attr({
        src: url
      });
      content_div.append(videoframe);
    } else {
      inhalt.text(title);
      inhalt.attr({
        id: sid
      });
      link.append($(inhalt));
    }
    info = $("<p>");
    info.addClass("referrer");
    info.text("Block: " + item.block);
    info1 = $("<p>");
    info1.addClass("referrer");
    info1.text(sid + " > " + item.sidref);
    info2 = $("<p>");
    info2.addClass("referrer");
    info2.text(vid + " > " + ref);
    content_div.addClass("content");
    content_div.append($(link));
    panel_div.addClass(special);
    panel_div.append(head_div);
    panel_div.append($(content_div));
    return $("#historycontent").append($(panel_div));
  };

  bookmarkIt = function(site, context) {
    var url;
    url = site.url;
    context = context;
    if (bookMarks[url] != null) {
      if (bookMarks[url].context === context) {
        return chrome.bookmarks.remove(bookMarks[url].bid, function() {
          return reload();
        });
      } else if (bookMarks[url].context !== void 0) {
        return chrome.bookmarks.remove(bookMarks[url].bid, function() {
          return createBookmark(site, context);
        });
      }
    } else {
      return createBookmark(site, context);
    }
  };

  createBookmark = function(site, context) {
    return chrome.bookmarks.getTree(function(bookmarkTreeNodes) {
      var bookmarkfolder, contextfolder, folder, m, newtitle, sub, _i, _j, _len, _len1, _ref;
      folder = bookmarkTreeNodes[0].children[1].children;
      newtitle = "" + site.vid + "___" + site.title;
      bookmarkfolder = void 0;
      contextfolder = void 0;
      for (_i = 0, _len = folder.length; _i < _len; _i++) {
        sub = folder[_i];
        if (sub.title === "conmarks") {
          bookmarkfolder = sub;
        }
      }
      _ref = sub.children;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        m = _ref[_j];
        if (context === m.title) {
          contextfolder = m;
          chrome.bookmarks.create({
            parentId: m.id,
            title: newtitle,
            url: site.url
          }, function() {});
          reload();
        }
      }
      if (contextfolder === void 0) {
        return chrome.bookmarks.create({
          parentId: sub.id,
          title: context
        }, function(bookmarkTreeNodes) {
          console.log(bookmarkTreeNodes);
          contextfolder = bookmarkTreeNodes;
          chrome.bookmarks.create({
            parentId: contextfolder.id,
            title: newtitle,
            url: site.url
          }, function() {});
          return reload();
        });
      }
    });
  };

}).call(this);
